

@baseUrl = http://localhost:3000/api
@contentType = application/json

###
# Obtener todos los héroes
GET {{baseUrl}}/heroes
Accept: {{contentType}}

###
# @name addSpiderMan
# Crear héroe: Spider-Man (Marvel)
POST {{baseUrl}}/heroes
Content-Type: {{contentType}}

{
  "name": "Spider-Man",
  "power": "Poderes arácnidos, sentido arácnido, fuerza sobrehumana",
  "universe": "Marvel",
  "isActive": true
}

###

# Recuperar el id del héroe creado
@spiderman_id = {{ addSpiderMan.response.body.data.id }}

###

# Recuperar el héroe por ID
GET {{baseUrl}}/heroes/{{spiderman_id}}
Accept: {{contentType}}



###
# @name addBatman
# Crear héroe: Batman (DC)
POST {{baseUrl}}/heroes
Content-Type: {{contentType}}

{
  "name": "Batman",
  "power": "Intelecto, artes marciales, tecnología avanzada",
  "universe": "DC",
  "isActive": true
}

###

@batman_id = {{ addBatman.response.body.data.id }}

###
# @name addWonderWoman
# Crear héroe: Wonder Woman (DC)
POST {{baseUrl}}/heroes
Content-Type: {{contentType}}

{
  "name": "Wonder Woman",
  "power": "Fuerza, agilidad, lazo de la verdad",
  "universe": "DC",
  "isActive": true
}

###

@wonderwoman_id = {{ addWonderWoman.response.body.data.id }}


###
# @name addIronMan
# Crear héroe: Iron Man (Marvel)
POST {{baseUrl}}/heroes
Content-Type: {{contentType}}

{
  "name": "Iron Man",
  "power": "Armadura tecnológica, genio inventor",
  "universe": "Marvel",
  "isActive": true
}

###

@ironman_id = {{ addIronMan.response.body.data.id }}

###
# Obtener héroes filtrando por universo (Marvel)
GET {{baseUrl}}/heroes?universe=Marvel
Accept: {{contentType}}

###
# Actualizar héroe (usar el ID del héroe creado anteriormente)
PUT {{baseUrl}}/heroes/{{spiderman_id}}
Content-Type: {{contentType}}

{
  "name": "Spider-Man",
  "power": "Poderes arácnidos mejorados, sentido arácnido, telarañas orgánicas",
  "universe": "Marvel",
  "isActive": true
}

###
# Eliminar héroe (usar el ID del héroe creado anteriormente)
DELETE {{baseUrl}}/heroes/{{spiderman_id}}
Accept: {{contentType}}

###
# Operaciones adicionales con ObjectIds dinámicos

# Actualizar Batman
PUT {{baseUrl}}/heroes/{{batman_id}}
Content-Type: {{contentType}}

{
  "name": "Batman",
  "power": "Intelecto superior, artes marciales, tecnología avanzada, detective",
  "universe": "DC",
  "isActive": true
}

###
# Obtener Wonder Woman por ID
GET {{baseUrl}}/heroes/{{wonderwoman_id}}
Accept: {{contentType}}

###
# Eliminar Iron Man
DELETE {{baseUrl}}/heroes/{{ironman_id}}
Accept: {{contentType}}


